### ISSUE TITLE
"\x82" from ASCII-8BIT to UTF-8 的错误

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/fastlane-plugin-app_info#2]
好久不打 adhoc 的包，今天测试打了一个报了 `"\x82" from ASCII-8BIT to UTF-8` 的错误，根据错误来看应该是 adhoc 的证书输出的问题

```
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-plugin-app_info-0.3.0/lib/fastlane/plugin/app_info/helper/app_info_helper.rb:53:in `app_to_json'
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-plugin-app_info-0.3.0/lib/fastlane/plugin/app_info/actions/app_info_action.rb:20:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
```

**Comment by icyleaf** [comment]
不确定跟 icyleaf/app_info#31 是否有关联性

**Comment by icyleaf** [comment]
> 不确定跟 [icyleaf/app_info#31](https://github.com/icyleaf/app_info/issues/31) 是否有关联性

问题找到了，是 ipa adhoc 包新的签名方式变了，导致新增了一个 DER-Encoded-Profile 的键值，他是一个二进制文件流无法解析造成的。

本 issue 的问题是在把数据转 json 的时候报错，感觉把上面的问题解决基本上就没啥问题了 :D
